version: '3.1'

services:
    db:
        image: postgres
        restart: always
        env_file:
          - .env

    server:
        build:
            context: .
        restart: always
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - .:/app
